### PR TITLE
Add Djaq to APIs section

### PR DESCRIPTION
**Pull request by DariaKnyazeva**

### CODE REVIEW

**Comment by jefftriplett** [comment]
Thank you for your contribution! 

Djaq has a lot of potential, but I'm a little worried about "No warranties about reliability, security or that it will work exactly as described." I don't have time to step through the code, but I don't want to recommend something that inadvertently adds a security violation on someone's website. 

I'll defer to @wsvincent and we might merge it later.

**Comment by DariaKnyazeva** [comment]
Hi Jeff,

Thank you for your feedback!

Yes the author is listing that it is pre-alpha version.

What is great about Djaq, we used it at work to build really quick
prototype (we have shortage of backend developers due to COVID crisis), and
our Frontend guy was just able to use the API.

Thank you again,
Daria Knyazeva

сб, 4 июля 2020 г. в 22:38, Jeff Triplett <notifications@github.com>:

**Comment by jefftriplett** [comment]
@DariaKnyazeva thank you for the reply. (Apologies for my rushed feedback btw. That sounds a bit harsher than I intended.) 

Our goal is to make sure we don't merge something that's more alpha than stable and that security message in the repo definitely caught my attention.

**Comment by jefftriplett** [comment]
Thank you!

**Pull request merged**
