### PR TITLE
Add django-docker-heroku-template

### PR DESCRIPTION
**Pull request by bfirsh**
Tooting my own horn a bit here, but none of these other boilerplates worked for me so I made my own. Hopefully as useful for others as it has been for me!

### CODE REVIEW

**Comment by jefftriplett** [comment]
This looks great. My only hesitation is that boilerplates are a bit of a challenge to include since there are so many and they tend to get out of date / unmaintained quickly. Let me think it over for a bit, but we'll keep the PR open so that others can see it.

**Comment by morenoh149** [comment]
As someone unfamiliar with parcel, it is unclear to me where the frontend is meant to go. I see in package.json a call to `parcel build`.

Also consider making your boilerplate a [github template](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by jefftriplett** [comment]
@bfirsh thank you for the contribution!

**Comment by bfirsh** [comment]
@jefftriplett thank you!

@morenoh149 fair point -- I've documented how static assets work in the readme.

Making it a GitHub template is a bit complicated I think, because it's currently designed to be used as a Django template (where `{{ project_name }}` is replaced, etc). That would be all broken if people created new repositories from a GitHub template.

**Pull request merged**
