### PR TITLE
add file-validator

### PR DESCRIPTION
**Pull request by rzashakeri**
This Library a Audio Validator For Django With d MIME type checking the magic numbers signature And Extension Use FileType Library

[django-audio-validator](https://github.com/rzashakeri/django-audio-validator)

### CODE REVIEW

**Comment by jefftriplett** [comment]
Thank you for this submission. This package looks really useful. Since this package is still relatively new, I'd like to give it a bit more time and watch the releases for a bit.

**Comment by rzashakeri** [comment]
With this library you can validate files based on extension, size, mimes and magic numbers

[file-validator](https://github.com/rzashakeri/file_validator)

**Comment by wsvincent** [comment]
Closing this for now. Very cool project but as @webology noted we'd like to see a little more traction before featuring in the repo.

**Comment by rzashakeri** [comment]
> Closing this for now. Very cool project but as @webology noted we'd like to see a little more traction before featuring in the repo.

Thank you
Good luck 🙏

**Pull request closed without merging**
