### PR TITLE
Add django-impersonate

### PR DESCRIPTION
**Pull request by davegaeddert**
Looks like you have a few of these already, but this one has been my favorite for a while. Still actively maintained but it's not on GitHub (the one on GitHub looks like a really old fork). Just thought I would mention it!

### CODE REVIEW

**Comment by jefftriplett** [comment]
@davegaeddert thank you for the contribution. 

django-impersonate looks great, but I'm a little concerned about adding it since its trove tags aren't updated to suggest it'll work with Django >3.0 or Python > 3.8 which tells me it's been a while since it was updated. There's nothing wrong with that, and I'm happy to look again if they update and push a new release.

**Comment by davegaeddert** [comment]
Fair enough. I might check with them and see -- It says the latest release was last week so I do think it is active.

(Good to know you look at those tags because I'm realizing I rarely do! Probably guilty of not updating those on my own packages.)

**Comment by davegaeddert** [comment]
@jefftriplett they pushed a new release with updated classifiers.
https://pypi.org/project/django-impersonate/

**Comment by jefftriplett** [comment]
@davegaeddert thank you for the suggestion and follow-up.

**Pull request merged**
