### PR TITLE
Add Django IDOM

### PR DESCRIPTION
**Pull request by Archmonger**
Django IDOM automagically links a Django project to a ReactJS front-end via websockets.

This enables developers to build interactive websites without ever needing to write a single line of JavaScript. Responsive web pages will be written in pure Python.

### CODE REVIEW

**Comment by wsvincent** [comment]
Hi @Archmonger, This looks very cool. We are going to feature it in the Django News newsletter soon. It's still a little young to be featured here, in our biased opinion, but we'll keep this PR open and if adoption takes off reconsider it for inclusion in the future.

**Comment by Archmonger** [comment]
@wsvincent [IDOM Core](https://github.com/idom-team/idom) is actually older than Django Unicorn. The only new thing here is the added convenience of a pre-configured Django websocket.

**Comment by Archmonger** [comment]
Bump

**Comment by Archmonger** [comment]
@wsvincent

**Pull request closed without merging**
