### PR TITLE
Add Forge

### PR DESCRIPTION
**Pull request by davegaeddert**
This is a private/paid repo right now, so I completely understand if you don't want to add it (although it looks like some others may be too). Totally self-serving — it's a project I just started and think it fits in with some of the others mentioned here. Thanks for considering it!

### CODE REVIEW

**Comment by jefftriplett** [comment]
@davegaeddert I would reach out to the Forge folks https://forge.laravel.com/ and the DSF to avoid some potential grief. Happy to re-look down the road after those ✅  are checked.

**Comment by davegaeddert** [comment]
Thanks @jefftriplett. Yeah I read a lot of the DSF materials (and have included a 10% donation in the price), but I'll reach out just to see if I missed anything. Over time I have started downplaying the "Django" word in some ways.

Is your question on Laravel just a copyright/trademark one? I can certainly double-check that if that's what you're thinking. I'd be surprised if there's any issue but it has raised some branding questions for me anyway!

**Comment by wsvincent** [comment]
Hi @davegaeddert,

I'm on the DSF Board so I can weigh in here. It is a trademark violation to have a paid product that uses the name Django or in its URL. [See here numbers 5 and 7.](https://www.djangoproject.com/trademarks/). Educational sites are allowed per #5 but not paid products like starter projects. We've had to enforce Django's trademark on them multiple times and it's why other Django starter projects don't have "django" in the name.

A key tenant of keeping Django's trademarks active is enforcing them so we do need you to remove Django from the URL and product name. Otherwise it's great to the Django ecosystem to have a starter project so I'm personally glad you've done this. And it also seems like it can be viable based on Cory's project and others.

Let me know if you need additional assistance from me or the DSF Board on this.

-Will

**Comment by davegaeddert** [comment]
Thanks @wsvincent! I guess my interpretation is that it does meet section 5? I think it meets all three of the points, so is it the interpretation of "website or product whose purpose is to organize, educate or inform the Django community"? (Not trying to be a pain, just want to make sure I understand since I did try to do it right!)

**Comment by jefftriplett** [comment]
> Is your question on Laravel just a copyright/trademark one? I can certainly double-check that if that's what you're thinking. I'd be surprised if there's any issue but it has raised some branding questions for me anyway!

The DSF is easier to navigate. My concern would be getting a letter from the Forge/Laravel folks since they have been in the space for a while. That said, they seem like super reasonable people so they might even give you a 👍

**Comment by wsvincent** [comment]
Hi Dave,

I know the language can confusing as it is legalese and deliberately doesn't define concrete examples of what "organize, educate, or inform" means. Previous DSF Boards spent quite a long time on the language with lawyers. The DSF Board always prefers when someone asks in advance to avoid a launch but several times a year there is a paid software product, including starter projects, on which this issue comes up and the Board must request the name/URL be changed.

Historically--ie long before my time on the Board--the trademark has been enforced on any paid software products which were viewed as not meeting the category of "organize, educate, or inform" and this includes starter projects. 

If you like I can run this by the Board for an official vote. 

-Will

**Comment by davegaeddert** [comment]
Hey Will,

Thanks for the background. I certainly don’t want to waste anyone’s time, but I wouldn’t mind running it by the board and learning a little more about the process/perspectives. I should have started that conversation earlier, and I apologize for that! One of those things that almost doesn't matter until you make something people are interested in (which until yesterday with HN, I wasn't sure would be the case anyway).

I suppose if I had to make an argument for myself (and if this is my chance to do so), I’d say that the goal is absolutely to “organize” *and* “educate”.

Too early to say that this is working, but having Forge be a community of Django users that can learn from each other is what I want to happen (“organize”). The bottom section of https://www.djangoforge.dev/ is all about this. The trademark ([FAQs specifically](https://www.djangoproject.com/trademarks/faq/)) seems to be written with in-person conferences in mind (in terms of “organizing”), but perhaps it could use a little language towards how this translates to the online world? Especially today? Forums, Slack, etc. — is charging for access to those much different than charging attendance to in-person conferences or meetups? From the "organize" perspective, I see Forge as a private forum and support group.
CleanShot 2022-03-24 at 11 13 26

“Educate” is foundational too. The documentation is intentionally public (https://www.djangoforge.dev/docs/) and I think there’s a lot that can be learned from it with or without the private repo itself (hopefully more as I go). I’m also working through some [“guides”](https://www.djangoforge.dev/guides/page-titles/) for content/code that won’t be built into the private repo itself, but again serve the purpose of publicly educating. A product like this is 90% about education in my opinion, not unlike a book or course, but the code is one step closer to being usable. In short, I’m not sure any of this works without a lot of education…

Anyway, that's the gist of why I thought it fit [point 5](https://www.djangoproject.com/trademarks/#products-and-services-serving-the-community) of the trademark usage. I totally understand that the goal of the trademark in the first place is to protect the brand and not let people run wild with it, and that it probably errs on the side of _not_ allowing usage (which I would do too). At a high level, the thing I think is worth considering at the moment (which may or may not be a new topic) is whether there is room for more business models than just books and courses (which are specifically called out in the FAQs). The format is slightly different, but the content is often very similar. It's not that "it is a trademark violation to have a paid product that uses the name Django or in its URL", but that there are some types of products where you can and others you can't? People like myself are trying to figure out how to get paid to contribute to the ecosystem (so we can do it full-time!), I just have no interest in literal books or courses but am super interested in that same type of content, packaged up to be more readily usable (removing more steps and barriers for people!).

I took extra care to make it *explicitly* clear that it is not an official Django product (in addition to not using the colors, logos, donating *10%* to the DSF) and I'll go ahead and change the H1 from "Django Forge" to just "Forge".
CleanShot 2022-03-24 at 11 12 11

The domain name seems like the main concern, which I will certainly change if that's the way it goes, but I'm not sure yet that it's _that different_ from selling books under https://djangobook.com/, https://djangoforprofessionals.com/, etc. It's pretty clear when you visit them that they aren't official, which would seem to be the main goal of the trademark license.

Appreciate your help on this! If we need to move to email, you can use dave.gaeddert at dropseed.dev. Thank you!

**Comment by wsvincent** [comment]
Hi Dave, I'm sharing this with the Board in our monthly meeting today. -Will

**Comment by davegaeddert** [comment]
Sounds good, thanks Will! I should give you a quick update too — I've shifted how Forge works and it is now a public / open-source package that actually wraps around Django (https://github.com/django-forge/forge, https://pypi.org/project/forge/) + a private "Forge Pro" repo/package (https://www.djangoforge.dev/pro/). So it's no longer just one big private repo that people have to pay for. The question about the djangoforge.dev domain (and maybe "django-forge" org name on GitHub) are still relevant, but the paid product is now just Forge Pro and the rest is completely available to the community.

Let me know if you have questions. Still playing out some aspects of this and documenting it, but I think it could be an interesting take on a "semi-curated Django experience".

**Comment by wsvincent** [comment]
Hi Dave,

Thanks for the update. I noticed the change actually. It's probably a smarter business model!

Our Board member who is a former lawyer was unable to attend the meeting so we're continuing the discussion with him via email. It's important for the DSF to revisit the legal things periodically. It's also the case that we definitely have enforced the trademark around all paid software, including starter kids, in the past. So there is both a precedence and fairness aspect.

I'll let you know when there's an update.

**Pull request closed without merging**
