### PR TITLE
Add DJ Checkup

### PR DESCRIPTION
**Pull request by stuartmaxwell**
I've been running the DJ Checkup website for the last couple of years and have run close to 6000 security scans over deployed Django websites. I took this over from the Pony Checkup site after Sasha decided to close it down.

In my opinion, this would make a good addition to the Security section. 

Cheers - Stuart.

### CODE REVIEW

**Comment by jefftriplett** [comment]
hi @stuartmaxwell, thank you for the pr/addition and for continuing the project. I just tried it out and my only quip is that all of the doc links point towards the 3.0 docs (instead of LTS or 4.0) which are deprecated. If you don't mind updating and re-pinging us we can look again.

**Comment by stuartmaxwell** [comment]
Hi @jefftriplett - really appreciate the feedback and that's something I had overlooked. Coincidentally, I was reading Adam Johnson's new book today and I'll follow his recommendation and link to the "/stable/" docs to keep the links fresh. I'll ping you when they are all up to date.

Cheers,
Stuart.

**Comment by stuartmaxwell** [comment]
I had some free time this evening, so have fixed up the links to the Django docs. The fixed links are:

- https://docs.djangoproject.com/en/stable/howto/deployment/checklist/#debug
- https://docs.djangoproject.com/en/stable/ref/clickjacking/
- https://docs.djangoproject.com/en/stable/ref/csrf/
- https://docs.djangoproject.com/en/stable/topics/http/sessions/#using-cookie-based-sessions
- https://docs.djangoproject.com/en/stable/ref/settings/#session-cookie-httponly

Cheers
Stuart

**Comment by jefftriplett** [comment]
@stuartmaxwell thank you for making that change and the contribution. That's also a nice tip from Adam (I think I'm guilty of linking to dev docs which I rarely if ever really want to do.

**Pull request merged**
